EGA-archive/LocalEGA

deploy/bootstrap/run.sh

I understand the `VAULT_..._KEY` discrepency was introduced when the environment variables were renamed.
The code and bootstrap need ajustements, as in PR#26.
However, the setup still uses the nbis images and the code was not injected in them.
With this change, the tests can run with the newly adjusted code, without failing.

Injecting the local changes into nbis images

---

deploy/Makefile
deploy/bootstrap/run.sh
deploy/bootstrap/settings.rc
lega/ingest.py
lega/notifications.py
lega/utils/amqp.py
lega/utils/storage.py
lega/verify.py
tests/_common/mq/get.py
tests/integration/inbox.bats
tests/integration/ingestion.bats
tests/integration/simple.bats
tests/unit/test_ingest.py
tests/unit/test_notifications.py
tests/unit/test_storage.py
tests/unit/test_verify.py

Using S3 as inbox backend storage
The storage module can read and write to either a POSIX file system or an S3 backend.
Ingestion now reads from an S3 backend in case the `--inbox-backend s3` is passed to the bootstrap script.
1) Added sections in the bootstrap script to spawn an S3 volume, and a Minio container on it.
2) Adjusted the configurations to make ingest.py point to that backend
3) Fixed a issue in the storage.py latest additions (generating the huge headers)
4) Adjusted the notification message that land in the inbox queue.
#15 
Fixes the huge header issue (not listed, but still existing)
Added a simple.bats with only one ingestion of a 1MB test file.
Calling `bats tests/integration/simple.bats` for simplicity and quick checking if it all works.
@dtitov: You can try that branch …

Using S3 as inbox backend storage

---

deploy/bootstrap/run.sh

Travis pulls the latest minio image, and our local machines might still use an old (and working) one.
The travis debug mode showed that the XML response from Minio was malformatted
Pinned to a working version
@jbygdell , @viklund : I think that helps solve the Travis differences.

Pinning the minio version

---

README.md

This is not harmful, but it will look nicer to have a proper badge on the main Readme.
Using the `master` branch, as the `dev` branch does not see to indicate any status.

use master branch for travis badge

---

deploy/bootstrap/run.sh

This is not harmful to keep it (since it is ignored),
but it causes docker to create a directory on the local file system.
That's a little ugly and this is cleaning it up.

Removing audit.sql mentions from bootstrap

---

deploy/images/db/download.sql
deploy/images/db/ebi.sql
deploy/images/db/grants.sql
deploy/images/db/main.sql

This commit changes the views from LocalEga to be compatible with
the current data-out code
This PR fixes #34 
I cannot include any tests right now until other issues are fixed. Also there is a new issue for the data out code because to access the s3 backend it uses the fileid instead of the filepath (https://github.com/EGA-archive/ega-data-api/issues/101)

Fix database view for data out

---

requirements.txt

Addresses this:
Also `aiohttp-jinja2` does not seem to be used anywhere, was used in fake CEGA-users.
1. from `requirements.txt` removed `aiohttp-jinja2`
2. updated `Jinja2` to `2.10.1` - seems to be installed by a dependent library

Remove jinja as dependency

---

requirements.txt

Fixing this warning:
1. Update `urlib3` version to `>=1.24.2`
I don't think we should stop pinning versions, but it seems this will happen on regular basis :( as we saw with #54 as well.

Update urlib3 version

---

.travis.yml
Dockerfile
deploy/bootstrap/run.sh
lega/utils/storage.py
tests/unit/test_storage.py

Resolving #45 and #46 
Handling POSIX permissions on the mountpoint.
This mostly boils down to finding a way to make what we want coincide with what docker is capable of.
* Adding a `--archive-backend` switch to the bootstrap (keeping `s3` as default, so nothing changes).
* File paths in the DB are now stored without the prefix where the archive is mounted. The latter is a configuration setting.
* The archive mountpoint is updated with `lega` as group owner, in the base image.
#45 and #46 
Maybe there is a way to solve it using different driver options available from docker, but I don't think it is worth spending the time, if we only want to fix it to run on Travis.
This is worth investigating from the deployement side.
@blankdots @omllobet

POSIX permissions

---

requirements.txt

It seems I introduced an error with #56, thus I am fixing it.
The error as reported by @norling :
Replicated on Python 3.6.6
`pip freeze | grep -v "^-e" | xargs pip uninstall -y`
`pip install -r requirements.txt`
Error log:
```
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25 which is incompatible.
ERROR: botocore 1.12.134 has requirement urllib3<1.25,>=1.20; python_version >= "3.4", but you'll have urllib3 1.25 which is incompatible.
Installing collected packages: pika, chardet, idna, multidict, yarl, async-timeout, attrs, idna-ssl, aiohttp, Pygments, alabaster, pytz, Babel, pyparsing, six, packaging, certifi, urllib3, requests, snowballstemmer, MarkupSafe, Jinja2, sphinxcontrib-websupport, docutils, imagesize, Sphinx, sphinx-rtd-theme, …
```

Fixing urllib3 because 1.25 causes issues

---

.travis.yml

Cucumber tests were commented out due to a compilation error.
This turns them back on.

Turning the cucmber tests back on

---

deploy/bootstrap/defs.sh
deploy/bootstrap/run.sh

In some places, I had forgotten to use `${PYTHONEXEC}`, and used `python`.
Basically `s/python/${PYTHONEXEC}/g`
#67 
Eventhough we call `${PYTHONEXEC}` everywhere, the issue is that the python code imports packages that do not exist in the standard library for `python2.7`, namely `secrets`.
Maybe they can be imported manually _before_ running the bootstrap.
The use of `${PYTHONEXEC}` was to allow the bootstrap to point to another python3 location, not to make it `python2.7`-compatible. (We won't support the latter).

Using PYTHONEXEC consistently across the bootstrap scripts

---

deploy/bootstrap/run.sh
lega/utils/storage.py

Updating the boto3 client call, to use the configuration settings about TLS.
This enables encryption, and server verification.
Client verification is trickier and I'm currently on it.
You can already merge that part if you wish, and I'll make another PR with the client verification, or you leave #71 open for a little longer.
Note: I am aware about the warning:
```/usr/local/lib/python3.6/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for archive has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)```
This is a separate concern, it has to do with the certificate generation.

Fixing the TLS connection for boto3

---

deploy/bootstrap/run.sh
lega/utils/storage.py
tests/unit/test_storage.py

Enables TLS for Minio.
In `run.sh`
```
- ../bootstrap/certs/data/inbox-s3-backend.cert.pem:/home/.minio/public.crt
- ../bootstrap/certs/data/inbox-s3-backend.sec.pem:/home/.minio/private.key
- ../bootstrap/certs/data/CA.inbox-s3-backend.cert.pem:/home/.minio/CAs/LocalEGA.crt
```
is replaced with
```
- ../bootstrap/certs/data/inbox-s3-backend.cert.pem:/root/.minio/certs/public.crt
- ../bootstrap/certs/data/inbox-s3-backend.sec.pem:/root/.minio/certs/private.key
- ../bootstrap/certs/data/CA.inbox-s3-backend.cert.pem:/root/.minio/CAs/LocalEGA.crt
```
And the same for vault (archive) Minio.
Fixes https://github.com/EGA-archive/LocalEGA/issues/69

Fix TLS for Minio

---

deploy/bootstrap/run.sh
lega/utils/storage.py
tests/unit/test_storage.py

Client verification towards the S3 backend.
* Adding the file paths to the conf.ini
* updating a parameter to the S3 client.
#69 , #71 
The code is enabled, but, honestly, it's hard to test it since I could not find how to enforce client verification in MinIO. I hope it's done, somehow, when specifying the combination of the 3 files: cacert, cert and key 🤞

S3 client verification

---

requirements.txt

pgpy depends on a newer version of cryptography then the one we pinned. Updating to a newer version fixes the pip installation of libraries. After this all the integration tests should work

Fix integration tests

---

lega/utils/amqp.py

We want to be able to config the entire application without referring to a config file.
The config lookup works by first checking for the <SECTION>_<VAR> env var and then looking for the specified <var> in the [<section>] of the config file. Checking for a specific section in the configuration then will only work if there is a configuration file, since sections are not a defined concept in the environment. The test is also unnecesary since the following var lookup will fail anyway if it's not present.
Removed one assertion.

Removed config assertion to enable config-file less config

---

deploy/Makefile
lega/utils/db.py
lega/utils/exceptions.py
lega/verify.py
tests/_common/helpers.bash
tests/integration/ingestion.bats

When a file is ingested, we fetch its session key and try to decrypt the body of the file with it.
Before doing the latter, we checks if the sha256 checksum of the session key is already contained in the database (for non-errored and non-cancelled files).
If so, we raise a User Error.
If not, we proceed with the decryption and store the checksum of the session key in the database. (Note, we are aware of the potential data-race there, but it is not a harmful one). 
One more tests has been enabled: Not ingesting twice the same file

Vault consistency

---

README.md
deploy/bootstrap/run.sh

Simulating the different network and segregating the services to its relevant networks.
For example, inbox has no access to the database.

Network separation

---

lega/conf/__init__.py

adding a consctructor for tuple to fix safeloader as it is missing it
When trying to parse tuple configuration for logging the following error occurs:
```
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
in "/usr/local/lib/python3.6/site-packages/lega/conf/loggers/default.yaml", line 24, column 14
```
This PR aims to fix it.
1. added the tuple constructor to SafeLoader
Identified in neicnordic/LocalEGA repo
@silverdaz for suggestion on the one-liner

Fix tuple parsing in Yaml SafeLoader

---

deploy/bootstrap/lega-entrypoint.sh
ingestion/Dockerfile
ingestion/lega/dispatcher.py
ingestion/mq/entrypoint.sh
tests/README.md
tests/robustness/mq.bats

Adding a mechanism to not lose the messages when LocalEGA is using the shovel to CentralEGA and CentralEGA is down (for a while, after a restart, for example).
The messages were backed by an ephemeral queue, but they are now backed by a durable queue and a shovel moves them to Central EGA (with the right routing key) when the connection succeeds.
This is akin to a [(reverse) federated queue, but lower-level](https://www.rabbitmq.com/distributed.html#shovel) and we don't need credentials to the LocalEGA instances
One more test was added for it: Central EGA goes down when the ingestion is complete, and the message is not lost after the restart.

Robust shovel

---

deploy/bootstrap/certs.cnf
deploy/bootstrap/certs.mk

This pull request increases the size of the generated keys in the bootstrap to 4096.
This is to avoid the error
`ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3991)`
produced in versions of openssl with an increased security level configured. See
[Openssl security level](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_callback.html)

Increase key size to 4096

---

ingestion/db/db.sql

When deriving a job id, in the case encrypted_checksums are used, we were using the field names from the backed table, instead of the view.
We tested the new code internally with encrypted_checksums too.

Fixing the field names in the pipeline DB
